import os

NUM_TO_STR = {1: "latest", 2: 'second', 3: 'third', 4: 'fourth', 5: 'fifth', 6: 'sixth', 7: 'seventh', 8: 'eighth', 9: 'ninth', 10: 'tenth', 11: 'eleventh', 12: 'twelfth', 13: 'thirteenth', 14: 'fourteenth', 15: 'fifteenth', 16: 'sixteenth', 17: 'seventeenth', 18: 'eighteenth', 19: 'nineteenth', 20: 'twentieth', 21: 'twenty-first', 22: 'twenty-second', 23: 'twenty-third', 24: 'twenty-fourth', 25: 'twenty-fifth', 26: 'twenty-sixth', 27: 'twenty-seventh', 28: 'twenty-eighth', 29: 'twenty-ninth', 30: 'thirtieth', 31: 'thirty-first', 32: 'thirty-second', 33: 'thirty-third', 34: 'thirty-fourth', 35: 'thirty-fifth', 36: 'thirty-sixth', 37: 'thirty-seventh', 38: 'thirty-eighth', 39: 'thirty-ninth', 40: 'fortieth', 41: 'forty-first', 42: 'forty-second', 43: 'forty-third', 44: 'forty-fourth', 45: 'forty-fifth', 46: 'forty-sixth', 47: 'forty-seventh', 48: 'forty-eighth', 49: 'forty-ninth', 50: 'fiftieth', 51: 'fifty-first', 52: 'fifty-second', 53: 'fifty-third', 54: 'fifty-fourth', 55: 'fifty-fifth', 56: 'fifty-sixth', 57: 'fifty-seventh', 58: 'fifty-eighth', 59: 'fifty-ninth', 60: 'sixtieth', 61: 'sixty-first', 62: 'sixty-second', 63: 'sixty-third', 64: 'sixty-fourth', 65: 'sixty-fifth', 66: 'sixty-sixth', 67: 'sixty-seventh', 68: 'sixty-eighth', 69: 'sixty-ninth', 70: 'seventieth', 71: 'seventy-first', 72: 'seventy-second', 73: 'seventy-third', 74: 'seventy-fourth', 75: 'seventy-fifth', 76: 'seventy-sixth', 77: 'seventy-seventh', 78: 'seventy-eighth', 79: 'seventy-ninth', 80: 'eightieth', 81: 'eighty-first', 82: 'eighty-second', 83: 'eighty-third', 84: 'eighty-fourth', 85: 'eighty-fifth', 86: 'eighty-sixth', 87: 'eighty-seventh', 88: 'eighty-eighth', 89: 'eighty-ninth', 90: 'ninetieth', 91: 'ninety-first', 92: 'ninety-second', 93: 'ninety-third', 94: 'ninety-fourth', 95: 'ninety-fifth', 96: 'ninety-sixth', 97: 'ninety-seventh', 98: 'ninety-eighth', 99: 'ninety-ninth', 100: 'one hundredth'}

HISTORY_ROUND_COLUMN = "round"
HISTORY_RANK_COLUMN = "rank"
HISTORY_PLAYER_COLUMN = "player"
HISTORY_DOCNO_COLUMN = "docno"
HISTORY_QUERY_ID_COLUMN = "query_id"
HISTORY_DOCUMENT_COLUMN = "document"
HISTORY_GAME_ID_COLUMN = "game_id"

GAME_HISTORY_COLUMNS = ["round", "player", "document", "not_clean_document", "rank", "score", "user_prompt", "system_prompt"]
PLAYER_HISTORY_COLUMNS = ["round", "document", "feedback"]

QUERY_DF_QUERY_COLUMN = "query"
QUERY_DF_QUERY_ID_COLUMN = "query_id"
QUERY_DF_DOCUMENT_COLUMN = "document"

XML_TOPIC_HEADER = "topic"
XML_NUMBER_HEADER = "number"
XML_QUERY_HEADER = "query"

CONFIG_COMPETITION_HEADER = "competition"
CONFIG_AGENTS_HEADER = "agents"
CONFIG_GAME_HEADER = "game"
CONFIG_INIT_DOCS_PATH_HEADER = "init_docs_path"
CONFIG_RANKERS_HEADER = "rankers"
CONFIG_ROUND_BY_ROUND_HEADER = "round_by_round"
CONFIG_LLM_HEADER = "llm"
CONFIG_LLM_MODEL_NAME_HEADER = "model_name"
CONFIG_GAME_ROUNDS_HEADER = "rounds"

DEFAULT_LLM_AGENT_DEPTH = 1

MLX_IDENTIFIER = "mlx-community/"
CLEANING_PROMPT = "Your task is to clean up the document generated by an LLM. Remove any headers, prefixes, or metadata such as \"This is the modified document\" or similar phrases that are not part of the actual content. Exclude statements that describe how the document was modified or its characteristics, such as its length or ranking. Specifically, omit sentences like the following:\n\n- [The text above is the extracted document part.]\n- The extracted document part:\n- [The document text remains unchanged.]\n- (The extracted document part ends here)\n- [Document text only, no modifications or additions made.]\n- [End of Document]\n- [The rest of the text is not the document part and will be ignored.]\n- [Document Text Only]\n- *Here is the document text you requested, unaltered:*\n- To improve the ranking\n- the document length is 147 words\n\nImportant: Do not change or modify the actual content of the document. Only remove unnecessary prefixes, headers, or metadata, leaving the original text of the document untouched and unaltered. The output should read naturally, without unnecessary formatting or markers."

CONFIG_FILE_NAME = "config.json"
COMPETITION_HISTORY_FILE_NAME = "competition_history.csv"
TRECTEXT_FILE_NAME = "output.trectext"

PROJECT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
OUTPUTS_DIR = os.path.join(PROJECT_DIR, "outputs")

LOGS_FOLDER = "logs"

AGENT_LOG_FILE = "agent.log"
LLM_AGENT_LOG_FILE = "llm_agent.log"
COMPETITION_LOG_FILE = "competition.log"
GAME_LOG_FILE = "game.log"
HUGGING_FACE_LLM_LOG_FILE = "hugging_face_llm.log"
LLM_LOG_FILE = "llm.log"
MLX_LLM_LOG_FILE = "mlx_llm.log"
QUERY_PARSER_LOG_FILE = "query_parser.log"
TREC_PARSER_LOG_FILE = "trec_parser.log"
LLM_PLAYER_LOG_FILE = "llm_player.log"
PLAYER_LOG_FILE = "player.log"
CONTRIEVER_LOG_FILE = "contriever.log"
E5_LOG_FILE = "e5.log"
EMBEDDING_RANKER_LOG_FILE = "embedding_ranker.log"
INDEX_RANKER_LOG_FILE = "index_ranker.log"
OKAPI_RANKER_LOG_FILE = "okapi_ranker.log"
RANKER_LOG_FILE = "ranker.log"

AGENT_LOG_NAME = "Agent"
LLM_AGENT_LOG_NAME = "LLM Agent"
COMPETITION_LOG_NAME = "Competition"
GAME_LOG_NAME = "Game"
HUGGING_FACE_LLM_LOG_NAME = "Hugging Face LLM"
LLM_LOG_NAME = "LLM"
MLX_LLM_LOG_NAME = "MLX LLM"
QUERY_PARSER_LOG_NAME = "Query Parser"
TREC_PARSER_LOG_NAME = "Trec Parser"
LLM_PLAYER_LOG_NAME = "LLM Player"
PLAYER_LOG_NAME = "Player"
CONTRIEVER_LOG_NAME = "Contriever"
E5_LOG_NAME = "E5"
EMBEDDING_RANKER_LOG_NAME = "Embedding Ranker"
INDEX_RANKER_LOG_NAME = "Index Ranker"
OKAPI_RANKER_LOG_NAME = "Okapi Ranker"
RANKER_LOG_NAME = "Ranker"